---
on:
  workflow_call:
    inputs:
      region:
        required: false
        default: 'europe-west1'
        type: string
        description: 'Region or zone for Google Artifact Registry (default: europe-west1)'
      type:
        required: false
        default: 'GCR'
        type: string
        description: 'Type of GCP registry to login (default: GCR)'

jobs:
  docker_login:
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Google Container Registry
        if: ${{ inputs.type == 'GCR'}}
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCLOUD_KEY }}

      - name: Login to Google Artifact Registry
        if: ${{ inputs.type == 'GAR' }}
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.region }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_GITHUB_SA_KEY }}
